### ISSUE TITLE
run*.py scripts do not import modules correctly

### ISSUE THREAD

**Issue by doubleaykay** [DragonMarionette/ciphers#1]
`runCaesar.py`, `runColumn.py`, and `runVig.py` import the cipher modules like `from Cipher.caesar import *`, which assumes that there is a subdirectory in the working directory named `Cipher`. When attempting to run one of these scripts, there is an import error.

Proposal: move `runCaesar.py`, `runColumn.py`, and `runVig.py` one directory up, and put a blank file called `__init__.py` in the `Cipher` directory.

**Comment by doubleaykay** [comment]
Read more about `__init__.py`: https://stackoverflow.com/a/4116384

**Comment by DragonMarionette** [comment]
Issue closed. Fixed imports by removing `Cipher.` from the import statements.
